#cloud-config
autoinstall:
  version: 1
  interactive-sections:
    - storage
    - identity
    - keyboard
  refresh-installer:
    update: true
    channel: latest/edge
  source:
    id: ubuntu-desktop-minimal
  locale: en_US.UTF-8
  keyboard:
    layout: fr
  timezone: Europe/Paris
  #codecs:
    #install: true
  #drivers:
    #install: true
  packages:
    - git
    - sudo
  updates: all
  snaps:
    - name: teams-for-linux
      channel: edge
      classic: false
  late-commands:
    - wget -O - "http://dumpscript.epitest.eu" > /target/tmp/dump.sh
    - curtin in-target --target=/target -- /bin/bash /tmp/dump.sh 
  user-data:
    runcmd:
      - git clone https://github.com/TheodoreGozard/epitech-emacs.git epitech-emacs
      - sudo -u "#1000" ./epitech-emacs/INSTALL.sh local
      - rm -rf epitech-emacs
      - git clone https://github.com/Epitech/vim-epitech.git epitech-vim
      - cd epitech-vim
      - sudo -u "#1000" ./install.sh local
      - cd .. && rm -rf epitech-vim
  shutdown: reboot
