#cloud-config
autoinstall:
  version: 1
  interactive-sections:
    - storage
    - identity
    - keyboard
  refresh-installer:
    update: true
    channel: latest/edge
  source:
    id: ubuntu-desktop-minimal
  locale: en_US.UTF-8
  keyboard:
    layout: fr
  timezone: Europe/Paris
  packages:
    - git
  updates: all
  snaps:
    - name: teams-for-linux
      channel: edge
      classic: false
  late-commands:
    - wget -O - "http://dumpscript.epitest.eu" > /target/tmp/dump.sh
    - curtin in-target --target=/target -- chmod +x /tmp/dump.sh
    - curtin in-target --target=/target -- /bin/bash /tmp/dump.sh 
  shutdown: reboot