server {
	server_name dump.epistone.fr;
	return 301 https://raw.githubusercontent.com/TheodoreGozard/epitech-dump/refs/heads/main/dump.sh;
}

server {
    server_name autoinstall.dump.epistone.fr;
    return 301 https://raw.githubusercontent.com/TheodoreGozard/epitech-dump/refs/heads/main/autoinstall.yaml;
}

server {
	server_name stumper.dump.epistone.fr;
	return 301 https://raw.githubusercontent.com/TheodoreGozard/epitech-dump/refs/heads/main/stumper/dump.sh;
}

server {
	server_name ssh.dump.epistone.fr;
	return 301 https://raw.githubusercontent.com/TheodoreGozard/epitech-dump/refs/heads/main/stumper/setup-ssh-key.sh;
}

server {
	server_name docs.dump.epistone.fr;
	return 301 https://raw.githubusercontent.com/TheodoreGozard/epitech-dump/refs/heads/main/docs/dump-doc.pdf;
}
