server {
	server_name dump.epistone.fr;
	return 301 https://raw.githubusercontent.com/TheodoreGozard/epitech-dump/refs/heads/main/dump.sh;
}

server {
	server_name dump.stumper.epistone.fr;
	return 301 https://raw.githubusercontent.com/TheodoreGozard/epitech-dump/refs/heads/main/stumper/dump.sh;
}

server {
	server_name dump.ssh.epistone.fr;
	return 301 https://raw.githubusercontent.com/TheodoreGozard/epitech-dump/refs/heads/main/stumper/setup-ssh-key.sh;
}
