name: Create and push docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Docker image on Github registry
        run: |
          docker build . --file Dockerfile --tag ghcr.io/theodoregozard/nginx-autoinstall:amd
          docker tag ghcr.io/theodoregozard/nginx-autoinstall:amd ghcr.io/theodoregozard/nginx-autoinstall:latest
          docker push ghcr.io/theodoregozard/nginx-autoinstall:amd
          docker push ghcr.io/theodoregozard/nginx-autoinstall:latest

      
