name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Docker image on Github registry
        run: |
          docker build . --file Dockerfile --tag ghcr.io/theodoregozard/nginx-autoinstall:amd
          docker tag ghcr.io/theodoregozard/nginx-autoinstall:amd ghcr.io/theodoregozard/nginx-autoinstall:latest
          docker push ghcr.io/theodoregozard/nginx-autoinstall:amd ghcr.io/theodoregozard/nginx-autoinstall:latest
  
  build-and-push-arm64:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Docker image on Github registry
        run: |
          docker build . --file Dockerfile --tag ghcr.io/theodoregozard/nginx-autoinstall:arm
          docker push ghcr.io/theodoregozard/nginx-autoinstall:arm
      
